import { useState } from 'react';
import { ArrowUpRight, Loader2, Wallet, List } from 'lucide-react';
import { Button } from './ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from './ui/dialog';
import { BrandImage } from './Brand';
import { useApp } from '../context/AppContext';
import { explorer, short } from '../lib/api';

export const PageHeading = ({ eyebrow, title, description, action }) => <div className="page-heading"><div><span className="small-label" data-testid="page-eyebrow">{eyebrow}</span><h1 data-testid="page-heading">{title}</h1>{description && <p data-testid="page-description">{description}</p>}</div>{action}</div>;
export const EmptyState = ({ title, description, action, id = 'empty-state' }) => <div className="empty-state" data-testid={id}><BrandImage testId={`${id}-logo`}/><h3 data-testid={`${id}-title`}>{title}</h3><p data-testid={`${id}-description`}>{description}</p>{action}</div>;
export const ConnectPrompt = () => {
  const { setWalletOpen } = useApp();
  return <div className="connect-prompt" data-testid="connect-prompt"><div><Wallet size={18}/><span>One wallet signature. Your own devnet workspace.</span></div><Button variant="outline" data-testid="connect-prompt-button" onClick={() => setWalletOpen(true)}>Connect wallet <ArrowUpRight size={15}/></Button></div>;
};
export const Loading = () => <div className="loading-state" data-testid="loading-state"><Loader2 className="spin" size={22}/> Loading your corner of TIPRR…</div>;
export const AssetIcon = ({ symbol = 'SOL' }) => <span className={`coin ${symbol === 'SOL' ? 'sol-coin' : 'custom-coin'}`}>{symbol === 'SOL' ? '≋' : symbol.slice(0, 1)}</span>;
export const StatusBadge = ({ status, id }) => <span data-testid={id} className={`status-badge status-${status?.toLowerCase()}`}>{status?.replaceAll('_', ' ')}</span>;
export const Transactions = ({ rows, prefix = 'transaction' }) => {
  const [selected, setSelected] = useState(null);
  return <><div className="transaction-list">{rows.map(row => <div className="transaction-row" data-testid={`${prefix}-${row.id}`} key={row.id}><div className="transaction-type-icon"><ArrowUpRight size={18} style={row.type === 'DEPOSIT' ? { transform: 'rotate(180deg)' } : {}}/></div><div className="transaction-name"><strong>{row.type === 'DEPOSIT' ? 'Deposit' : row.type === 'TIP' ? 'Tip sent' : 'Withdrawal'}</strong><span>{new Date(row.created_at).toLocaleString(undefined, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}{row.destination ? ` · ${short(row.destination)}` : ''}</span>{row.error && <p className="transaction-error" data-testid={`${prefix}-error-${row.id}`}>{row.error}</p>}</div><div className="transaction-value"><strong data-testid={`${prefix}-amount-${row.id}`}>{row.amount} {row.symbol}</strong><StatusBadge status={row.status} id={`${prefix}-status-${row.id}`}/></div><button className="icon-button" title="Transaction details" aria-label="Transaction details" data-testid={`${prefix}-details-${row.id}`} onClick={() => setSelected(row)}><List size={16}/></button>{row.signature && <a className="icon-button" href={explorer(row.signature)} target="_blank" rel="noreferrer" title="View transaction" data-testid={`${prefix}-explorer-${row.id}`}><ArrowUpRight size={16}/></a>}</div>)}</div><Dialog open={!!selected} onOpenChange={open => { if (!open) setSelected(null); }}><DialogContent className="tiprr-dialog" data-testid={`${prefix}-details-dialog`}><DialogHeader><DialogTitle data-testid={`${prefix}-details-title`}>Every detail, accounted for.</DialogTitle><DialogDescription data-testid={`${prefix}-details-description`}>Solana devnet transaction record.</DialogDescription></DialogHeader>{selected && <><dl className="transaction-details">{[['Type', selected.type], ['Asset', `${selected.amount} ${selected.symbol}`], ['Base units', selected.amount_base_units], ['Status', selected.status], ['Mint', selected.mint_address || 'Native SOL (no mint)'], ['From', selected.source || '—'], ['To', selected.destination || '—'], ['Created', new Date(selected.created_at).toLocaleString()], ['Signature', selected.signature || 'Not submitted yet']].map(([label, value]) => <div key={label}><dt>{label}</dt><dd data-testid={`${prefix}-detail-${label.toLowerCase().replaceAll(' ', '-')}`}>{value}</dd></div>)}</dl>{selected.signature && <a className="subtle-link" data-testid={`${prefix}-details-explorer`} href={explorer(selected.signature)} target="_blank" rel="noreferrer">View on Solana Explorer <ArrowUpRight size={14}/></a>}</>}</DialogContent></Dialog></>;
};